//! Native semantic types and pure invariants for Attention.
//!
//! This crate is independent from transport, persistence, scheduling, providers, and UI.

mod change;
mod command;
mod commit;
mod delivery;
mod error;
mod evaluate;
mod id;
mod idempotency;
mod inbox;
mod outbox;
mod port;
mod query;
mod reminder;
mod result;
mod revision;
mod semantic_error;
mod signal;
mod source;
mod source_order;
mod work_item;

pub use change::AffectedView;
pub use change::AttentionSnapshot;
pub use change::ChangeEvent;
pub use change::ChangeEventDraft;
pub use change::ChangeGap;
pub use change::ChangeKind;
pub use change::ChangePage;
pub use change::ChangesResult;
pub use change::CommitCursor;
pub use change::InboxEffects;
pub use command::*;
pub use commit::*;
pub use delivery::BoundedDeliveryText;
pub use delivery::ClaimOutcome;
pub use delivery::DeliveryCheckpoint;
pub use delivery::DeliveryClaim;
pub use delivery::DeliveryCompletionOutcome;
pub use delivery::DeliveryLeaseToken;
pub use delivery::DeliveryState;
pub use delivery::DeliveryStatus;
pub use delivery::ProviderMessageId;
pub use delivery::RenewOutcome;
pub use error::InvariantError;
pub use evaluate::*;
pub use id::AttentionSignalId;
pub use id::ChangeEventId;
pub use id::OutboxIntentId;
pub use id::ReminderFireId;
pub use id::ReminderId;
pub use id::SourceEntityId;
pub use id::SourceReceiptId;
pub use id::WorkItemId;
pub use idempotency::CanonicalFingerprint;
pub use idempotency::MutationIdempotencyKey;
pub use idempotency::MutationOperation;
pub use inbox::InboxEntry;
pub use outbox::DeliveryPurpose;
pub use outbox::DeliverySubject;
pub use outbox::OutboxDeduplicationKey;
pub use outbox::OutboxIntent;
pub use port::*;
pub use query::*;
pub use reminder::Reminder;
pub use reminder::ReminderFire;
pub use reminder::ReminderFireState;
pub use reminder::ReminderTarget;
pub use reminder::validate_unique_reminder_targets;
pub use result::*;
pub use revision::Revision;
pub use semantic_error::PortError;
pub use semantic_error::ResourceRef;
pub use semantic_error::SemanticError;
pub use signal::AttentionSignal;
pub use signal::SignalAttentionState;
pub use signal::SignalSourceLifecycle;
pub use source::ExternalEntityId;
pub use source::OccurrenceId;
pub use source::OccurrenceKey;
pub use source::SourceEntity;
pub use source::SourceEntityKey;
pub use source::SourceInstance;
pub use source::SourceKind;
pub use source::SourceReceipt;
pub use source_order::ClaimLimit;
pub use source_order::NormalizedSourceOrder;
pub use source_order::ObservedSourceAuthority;
pub use source_order::QueryLimit;
pub use source_order::SourceComparatorDomain;
pub use source_order::SourceOrderComparison;
pub use source_order::SourceOrderMode;
pub use source_order::SourceStateVersion;
pub use work_item::WorkItem;
pub use work_item::WorkItemLifecycle;
