[package]
name = "example-04-rest-idiomatic"
version = "0.1.0"
license = "MIT"
edition = "2024"
publish = false

[dependencies]
universal-tool-core = { version = "0.2.3", path = "../../universal-tool-core", features = ["rest"] }
tokio = { version = "1", features = ["full"] }
axum = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
schemars = { version = "0.8", features = ["uuid1", "chrono"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["serde", "v4"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["cors", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
