pub struct InstallAsset {
    pub rel_path: &'static str,
    pub contents: &'static str,
}

// Order matters: .opencode assets first, opencode.json last.
// Embedded contents live in `install_manifest_generated.rs` (generated by xtask sync)
// from repo-root `.opencode/**` and `opencode.json`.
#[path = "install_manifest_generated.rs"]
mod install_manifest_generated;

pub use install_manifest_generated::INSTALL_MANIFEST;

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;
    use std::collections::HashSet;

    #[test]
    fn manifest_ends_with_opencode_json() {
        assert_eq!(
            INSTALL_MANIFEST.last().map(|asset| asset.rel_path),
            Some("opencode.json")
        );
    }

    #[test]
    fn manifest_paths_are_relative_and_do_not_escape() {
        for asset in INSTALL_MANIFEST {
            let path = std::path::Path::new(asset.rel_path);
            assert!(
                !path.is_absolute(),
                "manifest path is absolute: {}",
                asset.rel_path
            );
            assert!(
                !path
                    .components()
                    .any(|component| matches!(component, std::path::Component::ParentDir)),
                "manifest path escapes repo root: {}",
                asset.rel_path
            );
        }
    }

    #[test]
    fn opencode_json_file_refs_are_in_manifest() {
        let opencode = INSTALL_MANIFEST
            .iter()
            .find(|asset| asset.rel_path == "opencode.json")
            .expect("manifest should include opencode.json");

        let parsed: Value =
            serde_json::from_str(opencode.contents).expect("opencode.json should be valid JSON");
        let mut file_refs = Vec::new();
        collect_file_refs(&parsed, &mut file_refs);

        let manifest_paths = INSTALL_MANIFEST
            .iter()
            .map(|asset| asset.rel_path)
            .collect::<HashSet<_>>();

        for file_ref in file_refs {
            let normalized = file_ref.strip_prefix("./").unwrap_or(&file_ref);
            assert!(
                manifest_paths.contains(normalized),
                "missing manifest entry for file ref: {file_ref} (normalized: {normalized})"
            );
        }
    }

    fn collect_file_refs(value: &Value, output: &mut Vec<String>) {
        match value {
            Value::String(string) => {
                if let Some(inner) = string
                    .strip_prefix("{file:")
                    .and_then(|value| value.strip_suffix('}'))
                {
                    output.push(inner.to_string());
                }
            }
            Value::Array(values) => values
                .iter()
                .for_each(|value| collect_file_refs(value, output)),
            Value::Object(object) => object
                .values()
                .for_each(|value| collect_file_refs(value, output)),
            Value::Null | Value::Bool(_) | Value::Number(_) => {}
        }
    }
}
