//! Domain-neutral wire-format types for the Attention JSON-RPC protocol.
//!
//! Use [`RpcRequest`], [`RpcNotification`], and [`RpcResponse`] for JSON-RPC envelopes,
//! [`HelloRequest`] and [`HelloResult`] for `rpc.hello` negotiation, and the crate-root
//! identifier, version, and [`WireTimestamp`] types for protocol values.

mod envelope;
mod error;
mod event;
mod hello;
mod id;
mod method;
mod mutation;
mod resource;
mod sync;
mod time;
mod value;
mod version;
mod worker;

pub use envelope::JsonRpcVersion;
pub use envelope::RpcNotification;
pub use envelope::RpcRequest;
pub use envelope::RpcResponse;
pub use envelope::RpcResponsePayload;
pub use error::CREATE_CONFLICT;
pub use error::CURSOR_GAP;
pub use error::CreateConflictData;
pub use error::DELIVERY_NOT_FOUND;
pub use error::DeliveryNotFoundData;
pub use error::EXPECTED_REVISION_CONFLICT;
pub use error::ErrorCode;
pub use error::ExpectedRevisionConflictData;
pub use error::HELLO_REQUIRED;
pub use error::IDEMPOTENCY_MISMATCH;
pub use error::INTERNAL_ERROR;
pub use error::INVALID_PARAMS;
pub use error::INVALID_REQUEST;
pub use error::IdempotencyMismatchData;
pub use error::METHOD_NOT_FOUND;
pub use error::OCCURRENCE_CONTENT_MISMATCH;
pub use error::OccurrenceContentMismatchData;
pub use error::PARSE_ERROR;
pub use error::ProtocolError;
pub use error::RESOURCE_NOT_FOUND;
pub use error::ResourceNotFoundData;
pub use error::ResourceRef;
pub use error::RpcError;
pub use error::SOURCE_VERSION_CONFLICT;
pub use error::SourceVersionConflictData;
pub use error::UNSUPPORTED_PROTOCOL_VERSION;
pub use error::V1_ERROR_CODES;
pub use error::V1Error;
pub use error::V1ErrorDecodeError;
pub use event::AffectedView;
pub use event::ChangeEvent;
pub use event::ChangeKind;
pub use event::InboxEffects;
pub use event::V1_CHANGE_KIND_NAMES;
pub use hello::AttentionHelloResult;
pub use hello::ClientIdentity;
pub use hello::HelloLimits;
pub use hello::HelloRequest;
pub use hello::HelloResult;
pub use hello::RPC_HELLO_METHOD;
pub use hello::SubscriptionRequest;
pub use hello::SubscriptionResult;
pub use id::AttentionSignalId;
pub use id::BootId;
pub use id::ChangeEventId;
pub use id::Cursor;
pub use id::MutationIdempotencyKey;
pub use id::OutboxIntentId;
pub use id::ProviderMessageId;
pub use id::ReminderFireId;
pub use id::ReminderId;
pub use id::RequestId;
pub use id::ResponseId;
pub use id::ServerId;
pub use id::SourceEntityId;
pub use id::SourceReceiptId;
pub use id::StreamId;
pub use id::WorkItemId;
pub use method::AttentionChange;
pub use method::AttentionSignalAcknowledge;
pub use method::AttentionSignalGet;
pub use method::AttentionSignalGetParams;
pub use method::ChangeNotificationParams;
pub use method::ChangesGet;
pub use method::ChangesGetParams;
pub use method::DeliveryClaim;
pub use method::DeliveryFailRetryable;
pub use method::DeliveryFailTerminal;
pub use method::DeliveryInspect;
pub use method::DeliveryRenew;
pub use method::DeliverySucceed;
pub use method::EmptyParams;
pub use method::ReminderCreate;
pub use method::ReminderFireAcknowledge;
pub use method::ReminderFireSnooze;
pub use method::ReminderGet;
pub use method::ReminderGetParams;
pub use method::RpcMethod;
pub use method::RpcNotificationMethod;
pub use method::SnapshotGet;
pub use method::SourceEntityGet;
pub use method::SourceEntityGetParams;
pub use method::SourceOccurrenceIngest;
pub use method::SourceReceiptGet;
pub use method::SourceReceiptGetParams;
pub use method::V1_METHOD_NAMES;
pub use method::V1_NOTIFICATION_METHOD_NAMES;
pub use method::WorkItemCancel;
pub use method::WorkItemComplete;
pub use method::WorkItemCreate;
pub use method::WorkItemGet;
pub use method::WorkItemGetParams;
pub use mutation::AcknowledgeAttentionSignalParams;
pub use mutation::AcknowledgeAttentionSignalResult;
pub use mutation::AcknowledgeReminderFireParams;
pub use mutation::AcknowledgeReminderFireResult;
pub use mutation::AttentionSignalMutationValue;
pub use mutation::CancelWorkItemParams;
pub use mutation::CancelWorkItemResult;
pub use mutation::CompleteWorkItemParams;
pub use mutation::CompleteWorkItemResult;
pub use mutation::CreateReminderParams;
pub use mutation::CreateReminderResult;
pub use mutation::CreateWorkItemParams;
pub use mutation::CreateWorkItemResult;
pub use mutation::IngestSourceOccurrenceParams;
pub use mutation::IngestSourceOccurrenceResult;
pub use mutation::MutationDisposition;
pub use mutation::MutationResult;
pub use mutation::ReceiptOnlyReason;
pub use mutation::ReminderMutationValue;
pub use mutation::SnoozeReminderFireParams;
pub use mutation::SnoozeReminderFireResult;
pub use mutation::SourceEntityIdentity;
pub use mutation::SourceIngestionDecision;
pub use mutation::SourceIngestionValue;
pub use mutation::WorkItemMutationValue;
pub use resource::AttentionSignalView;
pub use resource::ExternalEntityId;
pub use resource::InboxEntryKey;
pub use resource::InboxEntryView;
pub use resource::OccurrenceId;
pub use resource::OccurrenceKey;
pub use resource::ReminderFireState;
pub use resource::ReminderFireView;
pub use resource::ReminderTarget;
pub use resource::ReminderView;
pub use resource::SignalAttentionState;
pub use resource::SignalSourceLifecycle;
pub use resource::SourceEntityKey;
pub use resource::SourceEntityView;
pub use resource::SourceInstance;
pub use resource::SourceKind;
pub use resource::SourceOrder;
pub use resource::SourceOrderDomain;
pub use resource::SourceReceiptView;
pub use resource::V1_RESOURCE_VARIANT_NAMES;
pub use resource::WorkItemLifecycle;
pub use resource::WorkItemView;
pub use sync::AttentionSnapshot;
pub use sync::ChangesResult;
pub use sync::CursorGap;
pub use sync::CursorGapReason;
pub use sync::SnapshotRequired;
pub use sync::SnapshotResult;
pub use time::WireTimestamp;
pub use value::DeliveryLeaseToken;
pub use value::NormalizedSourceOrder;
pub use value::Revision;
pub use value::SourceStateVersion;
pub use version::PROTOCOL_V1;
pub use version::ProtocolVersion;
pub use worker::DeliveryAuthorityView;
pub use worker::DeliveryClaimCapability;
pub use worker::DeliveryClaimParams;
pub use worker::DeliveryClaimResult;
pub use worker::DeliveryCompletionOutcome;
pub use worker::DeliveryCompletionResult;
pub use worker::DeliveryFailRetryableParams;
pub use worker::DeliveryFailRetryableResult;
pub use worker::DeliveryFailTerminalParams;
pub use worker::DeliveryFailTerminalResult;
pub use worker::DeliveryInspectParams;
pub use worker::DeliveryInspectResult;
pub use worker::DeliveryPurpose;
pub use worker::DeliveryRenewParams;
pub use worker::DeliveryRenewResult;
pub use worker::DeliveryRenewalOutcome;
pub use worker::DeliveryStateView;
pub use worker::DeliverySubject;
pub use worker::DeliverySucceedParams;
pub use worker::DeliverySucceedResult;
pub use worker::OutboxIntentView;
pub use worker::V1_WORKER_VARIANT_NAMES;
