import { act, cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { App, canonicalizeLocalDateTime } from "../App";
import liveSourceChange from "./fixtures/live-source-change.json";
import type { DesktopBridge } from "../bridge";
import type {
  DesktopCommandError,
  DesktopMessage,
  MutationReceipt,
  SnapshotState,
} from "../presentation";

const hostile = '<img src=x onerror="window.pwned=true"> https://evil.example';
afterEach(cleanup);
const work = { id: hostile, revision: "7", lifecycle: "open" as const };
const signal = {
  id: "signal-1",
  revision: "8",
  sourceLifecycle: "resolved" as const,
  attentionState: "unread" as const,
};
const acknowledgedSignal = {
  id: "signal-ack",
  revision: "9",
  sourceLifecycle: "active" as const,
  attentionState: "acknowledged" as const,
};
const fire = {
  id: "fire-1",
  triggerAt: "2026-01-01T00:00:00.000000Z",
  state: "fired" as const,
};
const snapshot: SnapshotState = {
  workItems: [work],
  attentionSignals: [signal, acknowledgedSignal],
  reminders: [],
  inbox: [
    { kind: "work_item", workItem: work },
    { kind: "attention_signal", attentionSignal: signal },
    { kind: "attention_signal", attentionSignal: acknowledgedSignal },
    {
      kind: "reminder_fire",
      reminderId: "reminder-1",
      reminderRevision: "10",
      target: { kind: "work_item", workItemId: work.id },
      fire,
    },
  ],
};

function receipt(id: string): MutationReceipt {
  return {
    disposition: "applied",
    cursor: `cursor-${id}`,
    changeEventId: `event-${id}`,
    resource: { kind: "work_item", id },
  };
}

function harness(initial: SnapshotState = snapshot) {
  let handler: ((message: DesktopMessage) => void) | undefined;
  const api: DesktopBridge = {
    state: vi.fn(async () => ({
      sequence: 1,
      generation: 1,
      status: { kind: "connected" as const },
      snapshot: initial,
      snapshotAfterCursor: "cursor-1",
      replay: [],
    })),
    acknowledgeSnapshot: vi.fn(async () => {}),
    acknowledgeChange: vi.fn(async () => {}),
    subscribe: vi.fn(async (next) => {
      handler = next;
      return () => {};
    }),
    createWorkItem: vi.fn(async () => receipt("created")),
    completeWorkItem: vi.fn(async () => receipt("completed")),
    cancelWorkItem: vi.fn(async () => receipt("cancelled")),
    acknowledgeAttentionSignal: vi.fn(async () => receipt("signal")),
    createReminder: vi.fn(async () => receipt("reminder")),
    acknowledgeReminderFire: vi.fn(async () => receipt("fire")),
    snoozeReminderFire: vi.fn(async () => receipt("snooze")),
  };
  return {
    api,
    emit: async (message: DesktopMessage) => {
      if (!handler) throw new Error("not subscribed");
      await act(async () => handler?.(message));
    },
  };
}

async function ready(api: DesktopBridge) {
  await waitFor(() => expect(api.state).toHaveBeenCalled());
  await screen.findByText(hostile);
}

describe("Inbox mutation UI", () => {
  it("renders the exact DTO generated by the live supervisor/server/Turso path", async () => {
    const empty: SnapshotState = {
      workItems: [],
      attentionSignals: [],
      reminders: [],
      inbox: [],
    };
    const mock = harness(empty);
    render(<App api={mock.api} />);
    await waitFor(() => expect(mock.api.state).toHaveBeenCalled());
    expect(screen.getByText("Your inbox is clear.")).toBeVisible();

    await mock.emit(liveSourceChange as DesktopMessage);
    const liveText = "01912345-6789-7abc-8def-0123456789ab";
    expect(screen.getByText(liveText)).toBeVisible();
    expect(screen.getByText(/active; unread; revision 1/)).toBeVisible();
    expect(document.querySelector("img")).toBeNull();
    expect(document.querySelector("a")).toBeNull();
    expect(mock.api.acknowledgeChange).toHaveBeenCalledWith(1, "LIVE_CURSOR");
  });

  it("canonicalizes valid local values to UTC RFC3339 microseconds and rejects invalid values", () => {
    const [wholeSeconds] = new Date(2026, 4, 6, 7, 8, 9, 120).toISOString().split(".");
    const expected = `${wholeSeconds}.120000Z`;
    expect(canonicalizeLocalDateTime("2026-05-06T07:08:09.12")).toBe(expected);
    expect(() => canonicalizeLocalDateTime("2026-02-30T10:00")).toThrow(/valid local/);
    expect(() => canonicalizeLocalDateTime("not-a-date")).toThrow(/valid local/);
  });

  it("renders every authoritative branch literally and exercises all seven controls", async () => {
    const mock = harness();
    render(<App api={mock.api} />);
    await ready(mock.api);

    expect(screen.getAllByText("Attention signal")).toHaveLength(2);
    expect(screen.getByText("Reminder fire")).toBeVisible();
    expect(screen.getByText(/resolved; unread; revision 8/)).toBeVisible();
    expect(screen.getByText(hostile)).toBeVisible();
    expect(document.querySelector("img")).toBeNull();
    expect(document.querySelector("a")).toBeNull();

    const dates = screen.getAllByLabelText(/Due|Scheduled|Defer until/);
    fireEvent.change(dates[0], { target: { value: "2026-05-06T07:08" } });
    fireEvent.click(screen.getByRole("button", { name: "Create work item" }));
    await waitFor(() =>
      expect(mock.api.createWorkItem).toHaveBeenCalledWith({
        dueAt: canonicalizeLocalDateTime("2026-05-06T07:08"),
        scheduledAt: undefined,
        deferUntil: undefined,
      }),
    );

    const workArticle = screen.getByText(hostile).closest("article");
    if (!workArticle) throw new Error("missing work article");
    fireEvent.click(within(workArticle).getByRole("button", { name: "Complete" }));
    fireEvent.click(within(workArticle).getByRole("button", { name: "Cancel" }));
    expect(mock.api.completeWorkItem).toHaveBeenCalledWith({ id: hostile, expectedRevision: "7" });
    expect(mock.api.cancelWorkItem).toHaveBeenCalledWith({ id: hostile, expectedRevision: "7" });

    const signalArticle = screen.getByText("signal-1").closest("article");
    if (!signalArticle) throw new Error("missing signal article");
    fireEvent.click(within(signalArticle).getByRole("button", { name: "Acknowledge" }));
    expect(mock.api.acknowledgeAttentionSignal).toHaveBeenCalledWith({
      id: "signal-1",
      expectedRevision: "8",
    });

    fireEvent.change(screen.getByLabelText("Target"), { target: { value: `work:${hostile}` } });
    fireEvent.change(screen.getByLabelText("Trigger at"), {
      target: { value: "2026-06-01T12:30" },
    });
    fireEvent.click(screen.getByRole("button", { name: "Create reminder" }));
    await waitFor(() =>
      expect(mock.api.createReminder).toHaveBeenCalledWith({
        target: { kind: "work_item", workItemId: hostile },
        triggerAt: canonicalizeLocalDateTime("2026-06-01T12:30"),
      }),
    );

    const fireArticle = screen.getByText("fire-1").closest("article");
    if (!fireArticle) throw new Error("missing fire article");
    fireEvent.click(within(fireArticle).getByRole("button", { name: "Acknowledge" }));
    fireEvent.change(within(fireArticle).getByLabelText("Snooze until"), {
      target: { value: "2026-06-02T13:45" },
    });
    fireEvent.click(within(fireArticle).getByRole("button", { name: "Snooze" }));
    expect(mock.api.acknowledgeReminderFire).toHaveBeenCalledWith({
      reminderId: "reminder-1",
      fireId: "fire-1",
      expectedRevision: "10",
    });
    await waitFor(() =>
      expect(mock.api.snoozeReminderFire).toHaveBeenCalledWith({
        reminderId: "reminder-1",
        fireId: "fire-1",
        expectedRevision: "10",
        replacementTriggerAt: canonicalizeLocalDateTime("2026-06-02T13:45"),
      }),
    );

    // Receipts alone never change authoritative Inbox materialization.
    expect(screen.getByText(hostile)).toBeVisible();
    expect(screen.getByText("fire-1")).toBeVisible();
  });

  it("applies exact event effects, including removal of active+acknowledged signals", async () => {
    const mock = harness();
    render(<App api={mock.api} />);
    await ready(mock.api);
    expect(screen.getByText("signal-ack")).toBeVisible();
    await mock.emit({
      type: "change",
      sequence: 2,
      generation: 1,
      event: {
        id: "event-remove",
        cursor: "cursor-2",
        occurredAt: "now",
        kind: "signal_changed",
        affected: [],
        inbox: {
          upserts: [],
          removals: [{ kind: "attention_signal", attentionSignalId: "signal-ack" }],
        },
      },
    });
    expect(screen.queryByText("signal-ack")).toBeNull();
    expect(screen.getByText("signal-1")).toBeVisible();
  });

  it("shows conflict and ambiguity independently", async () => {
    const mock = harness();
    vi.mocked(mock.api.completeWorkItem).mockRejectedValue({
      category: "expected_revision_conflict",
      message: "changed",
      resourceKind: "work_item",
      resourceId: hostile,
      expectedRevision: "7",
      actualRevision: "8",
    } satisfies DesktopCommandError);
    vi.mocked(mock.api.cancelWorkItem).mockRejectedValue({
      category: "ambiguous_mutation",
      message: "connection lost",
    } satisfies DesktopCommandError);
    render(<App api={mock.api} />);
    await ready(mock.api);
    const article = screen.getByText(hostile).closest("article");
    if (!article) throw new Error("missing work article");
    fireEvent.click(within(article).getByRole("button", { name: "Complete" }));
    fireEvent.click(within(article).getByRole("button", { name: "Cancel" }));
    expect(await screen.findByText(/changed from revision 7 to 8/)).toBeVisible();
    expect(await screen.findByText(/Outcome unknown: connection lost/)).toBeVisible();
  });

  it("preserves drafts through reset and replacement snapshot while reconciling awaiting success", async () => {
    const mock = harness();
    render(<App api={mock.api} />);
    await ready(mock.api);
    const due = screen.getByLabelText("Due");
    fireEvent.change(due, { target: { value: "2026-05-06T07:08" } });
    fireEvent.click(screen.getByRole("button", { name: "Create work item" }));
    await screen.findByText(/Waiting for synchronized update/);
    await mock.emit({ type: "reset", sequence: 2, generation: 2, reason: "gap" });
    expect(due).toHaveValue("2026-05-06T07:08");
    await mock.emit({
      type: "snapshot",
      sequence: 3,
      generation: 2,
      state: snapshot,
      afterCursor: "fresh",
    });
    await mock.emit({
      type: "status",
      sequence: 4,
      generation: 2,
      status: { kind: "connected" },
    });
    expect(due).toHaveValue("2026-05-06T07:08");
    expect(screen.getByRole("button", { name: "Create work item" })).toBeEnabled();
  });
});
