[package]
name = "test-simple"
version = "0.1.0"
edition = "2024"

[dependencies]
universal-tool-core = { path = "../../universal-tool-core", features = ["cli"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
