use anyhow::Context;
use anyhow::Result;
use anyhow::bail;
use std::fmt::Write as _;
use std::fs;
use std::io::ErrorKind;
use std::path::Component;
use std::path::Path;

pub const GENERATED_PATH: &str = "apps/agentic/src/commands/install_manifest_generated.rs";

const ASSET_PATHS: &[&str] = &[
    ".opencode/sysprompt.md",
    ".opencode/sysprompt_gpt54.md",
    ".opencode/orchestrator_sysprompt.md",
    ".opencode/orchestrator_sysprompt_gpt54.md",
    ".opencode/review_sysprompt.md",
    ".opencode/review_sysprompt_gpt54.md",
    ".opencode/command/bash.md",
    ".opencode/command/capture_pr_comments_openai.md",
    ".opencode/command/commit.md",
    ".opencode/command/create_plan_final.md",
    ".opencode/command/create_plan_init.md",
    ".opencode/command/decide_findings_openai.md",
    ".opencode/command/describe_pr.md",
    ".opencode/command/discord.md",
    ".opencode/command/frame_openai.md",
    ".opencode/command/implement_plan.md",
    ".opencode/command/linear.md",
    ".opencode/command/linear_ticket_2_pr.md",
    ".opencode/command/linear_ticket_design_brief.md",
    ".opencode/command/openai.md",
    ".opencode/command/playwright.md",
    ".opencode/command/research.md",
    ".opencode/command/resolve_pr_ci_failures.md",
    ".opencode/command/resolve_pr_comments.md",
    ".opencode/command/resume_work_openai.md",
    ".opencode/command/review.md",
    ".opencode/command/review_pr_comments.md",
    ".opencode/command/sync_with_main_and_resolve_conflicts.md",
    ".opencode/command/unwind_openai.md",
    "opencode.json",
];

pub fn sync_install_manifest_generated(ws_root: &Path, dry_run: bool, check: bool) -> Result<bool> {
    if ASSET_PATHS.last().copied() != Some("opencode.json") {
        bail!("internal error: ASSET_PATHS must end with opencode.json");
    }

    let desired = render_generated_module(ws_root)?;
    let out_path = ws_root.join(GENERATED_PATH);

    let current = match fs::read_to_string(&out_path) {
        Ok(contents) => contents,
        Err(error) if error.kind() == ErrorKind::NotFound => String::new(),
        Err(error) => {
            return Err(error).with_context(|| format!("Failed to read {}", out_path.display()));
        }
    };

    let changed = current != desired;
    if !changed {
        return Ok(false);
    }

    if check {
        bail!("{GENERATED_PATH} is out of date; run `cargo run -p xtask -- sync`");
    }

    if dry_run {
        eprintln!("[sync] Would update {GENERATED_PATH} (dry-run)");
        return Ok(true);
    }

    fs::write(&out_path, desired)
        .with_context(|| format!("Failed to write {}", out_path.display()))?;
    eprintln!("[sync] Updated {GENERATED_PATH}");
    Ok(true)
}

fn render_generated_module(ws_root: &Path) -> Result<String> {
    let mut out = String::new();
    out.push_str("// @generated by xtask sync. DO NOT EDIT.\n");
    out.push_str("// Source of truth: repo-root `.opencode/**` and `opencode.json`.\n");
    out.push_str("// Regenerate with: `cargo run -p xtask -- sync`\n\n");
    out.push_str("use super::InstallAsset;\n\n");
    out.push_str("// Order matters: .opencode assets first, opencode.json last.\n");
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub const INSTALL_MANIFEST: &[InstallAsset] = &[\n");

    for rel_path in ASSET_PATHS {
        ensure_safe_rel_path(rel_path)?;

        let abs_path = ws_root.join(rel_path);
        let contents = fs::read_to_string(&abs_path)
            .with_context(|| format!("Failed to read source asset {}", abs_path.display()))?;

        out.push_str("    InstallAsset {\n");
        let _ = writeln!(out, "        rel_path: {rel_path:?},");
        out.push_str("        contents: ");
        out.push_str(&raw_string_literal(&contents));
        out.push_str(",\n");
        out.push_str("    },\n");
    }

    out.push_str("];\n");
    Ok(out)
}

fn ensure_safe_rel_path(rel_path: &str) -> Result<()> {
    let path = Path::new(rel_path);
    if path.is_absolute() {
        bail!("install-manifest generator path is absolute: {rel_path}");
    }
    if path
        .components()
        .any(|component| matches!(component, Component::ParentDir))
    {
        bail!("install-manifest generator path contains '..': {rel_path}");
    }
    Ok(())
}

fn raw_string_literal(contents: &str) -> String {
    let hashes = "#".repeat(required_hashes(contents));
    format!("r{hashes}\"{contents}\"{hashes}")
}

fn required_hashes(contents: &str) -> usize {
    let bytes = contents.as_bytes();
    let mut max_run = 0usize;
    let mut saw_quote = false;

    for i in 0..bytes.len() {
        if bytes[i] != b'"' {
            continue;
        }

        saw_quote = true;

        let mut run = 0usize;
        let mut j = i + 1;
        while j < bytes.len() && bytes[j] == b'#' {
            run += 1;
            j += 1;
        }
        max_run = max_run.max(run);
    }

    if saw_quote { max_run + 1 } else { 0 }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn raw_string_literal_increases_hashes_to_avoid_terminator() {
        let literal = raw_string_literal("a\"#b");
        assert!(literal.starts_with("r##\""), "expected 2 hashes: {literal}");
        assert!(literal.ends_with("\"##"), "expected 2 hashes: {literal}");
    }

    #[test]
    fn raw_string_literal_handles_multiple_hash_runs() {
        let literal = raw_string_literal("a\"###b");
        assert!(
            literal.starts_with("r####\""),
            "expected 4 hashes: {literal}"
        );
        assert!(literal.ends_with("\"####"), "expected 4 hashes: {literal}");
    }

    #[test]
    fn raw_string_literal_uses_zero_hashes_without_quotes() {
        let literal = raw_string_literal("plain markdown\n");
        assert_eq!(literal, "r\"plain markdown\n\"");
    }
}
