[target.'cfg(all(target_os = "macos", target_arch = "aarch64"))'] 
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-Wl,-rpath,$ORIGIN"]

[env]
# Set this to run integration tests that require mount permissions
# THOUGHTS_INTEGRATION_TESTS = "1"

[alias]
test-unit = "test --lib"
test-integration = "test --test mount_integration -- --nocapture"
test-all = "test --all-features"