[package]
name = "example-01-cli-simple"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
universal-tool-core = { path = "../../universal-tool-core", features = ["cli"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"