[package]
name = "example-03-rest-simple"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
universal-tool-core = { path = "../../universal-tool-core", features = ["rest"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
schemars = { version = "0.8", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"