name: Publish

on:
  push:
    tags:
      - '*-v*'

permissions:
  contents: write

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.89
      
      - name: Determine package from tag
        id: package
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          if [[ $TAG == thoughts-tool-* ]]; then
            echo "dir=thoughts_tool" >> $GITHUB_OUTPUT
          elif [[ $TAG == universal-tool-* ]]; then
            echo "dir=universal_tool" >> $GITHUB_OUTPUT
          elif [[ $TAG == claudecode-* ]]; then
            echo "dir=claudecode_rs" >> $GITHUB_OUTPUT
          fi
      
      - name: Publish package
        run: |
          cd ${{ steps.package.outputs.dir }}
          cargo publish --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      
      - name: Extract changelog
        id: changelog
        run: |
          cargo install git-cliff
          CHANGELOG=$(git cliff --latest --strip all)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false